baseURL = 'https://research.modelcitizendeveloper.com/'
languageCode = 'en-us'
title = 'Survey of Software - Research Library'
theme = 'hugo-book'

# Book theme specific config
[params]
  # Show page navigation and menu
  BookShowPageHeader = true
  BookMenuHeader = true
  BookMenu = true
  BookToC = 3

  # Specify section of content to render as menu
  BookSection = 'survey'

  # Enable search
  BookSearch = true

# Disable taxonomy (not needed for documentation)
disableKinds = ['taxonomy', 'taxonomyTerm']

# Enable HTML in Markdown (for details/summary tabs)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.after]]
    name = "What is this?"
    url = "/survey/taxonomy-1.3xx-vision"
    weight = 1

  [[menu.after]]
    name = "The Vision"
    url = "/vision/"
    weight = 2

  [[menu.after]]
    name = "Method"
    url = "/survey/method"
    weight = 3

  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/modelcitizendeveloper/survey-of-software"
    weight = 10
